/**
 * QBurst — one million points, binned into a density grid.
 *
 * The resume says "1M+ rows visualised with sub-second latency"; `pointCount` (from
 * `content.ts`) is that real, resume-traced figure and this module plots exactly that many
 * points, generated by a seeded, deterministic PRNG (`mulberry32`, `prng.ts`) so two builds
 * are byte-identical.
 *
 * The four-cluster layout below is a rendering choice, not a measurement — there is no
 * underlying QBurst dataset for this rebuild to sample from, so the *shape* of the scatter
 * is illustrative. Only the count is a claim. Task 6.3's caption says so on the page.
 *
 * Binning, not the raw 1,000,000 points, is the geometry this module hands off: Task 6.3
 * renders density cells, quantised to a handful of levels so it can emit one `<path>` per
 * level instead of one element per cell. "Resolving" means going from a coarse grid to a
 * fine one; the coarse grid here is not generated separately, it is the fine grid's cells
 * summed in 4×4 blocks, which is what makes their sums identical by construction rather
 * than by chance.
 *
 * Pure geometry, no DOM. Runs at build time (Astro frontmatter) — 1,000,000 iterations cost
 * build time, never visitor JS.
 */

import type { ScatterDiagramData } from './types';
import { mulberry32 } from './prng';
import { clamp01 } from './util';

export interface DensityGrid {
  cols: number;
  rows: number;
  /** Raw point count per cell, row-major, length `cols * rows`. Sums to `pointCount`. */
  counts: number[];
  /** The same counts quantised into `LEVEL_COUNT` density levels. 0 = empty cell. */
  levels: number[];
}

export interface ScatterGeometry {
  /** The full-detail grid. */
  fine: DensityGrid;
  /** `fine`, coarsened by summing 4×4 blocks — the "resolving from" state. */
  coarse: DensityGrid;
}

/** A "handful" of density levels — few enough that 6.3 emits one `<path>` per level. */
export const LEVEL_COUNT = 5;

const FINE_COLS = 48;
const FINE_ROWS = 48;
const COARSE_COLS = 12;
const COARSE_ROWS = 12;
const BLOCK_COLS = FINE_COLS / COARSE_COLS;
const BLOCK_ROWS = FINE_ROWS / COARSE_ROWS;

/**
 * Seed for the scatter's PRNG. Not a resume figure — an implementation constant, fixed so
 * every build produces the identical point cloud ("two runs are byte-identical").
 */
const SEED = 0x51a17e5;

/** Illustrative cluster centres and spreads — see the module doc comment. Normalised 0..1. */
const CLUSTERS: ReadonlyArray<{ cx: number; cy: number; sigma: number }> = [
  { cx: 0.28, cy: 0.32, sigma: 0.1 },
  { cx: 0.7, cy: 0.24, sigma: 0.13 },
  { cx: 0.58, cy: 0.72, sigma: 0.16 },
  { cx: 0.2, cy: 0.78, sigma: 0.08 },
];

/** Box-Muller: two independent standard-normal values from two uniform (0,1) draws. */
function gaussianPair(rand: () => number): [number, number] {
  const u1 = Math.max(rand(), Number.EPSILON); // avoid log(0)
  const u2 = rand();
  const r = Math.sqrt(-2 * Math.log(u1));
  const theta = 2 * Math.PI * u2;
  return [r * Math.cos(theta), r * Math.sin(theta)];
}

function quantiseLevels(counts: readonly number[]): number[] {
  let max = 0;
  for (const count of counts) if (count > max) max = count;
  return counts.map((count) => {
    if (count === 0 || max === 0) return 0;
    return Math.min(LEVEL_COUNT - 1, Math.ceil((count / max) * (LEVEL_COUNT - 1)));
  });
}

export function scatterGeometry(data: ScatterDiagramData): ScatterGeometry {
  const rand = mulberry32(SEED);
  const fineCounts = new Array<number>(FINE_COLS * FINE_ROWS).fill(0);

  for (let i = 0; i < data.pointCount; i++) {
    const cluster = CLUSTERS[Math.floor(rand() * CLUSTERS.length) % CLUSTERS.length];
    const [z0, z1] = gaussianPair(rand);
    const x = clamp01(cluster.cx + z0 * cluster.sigma);
    const y = clamp01(cluster.cy + z1 * cluster.sigma);
    const col = Math.min(FINE_COLS - 1, Math.floor(x * FINE_COLS));
    const row = Math.min(FINE_ROWS - 1, Math.floor(y * FINE_ROWS));
    fineCounts[row * FINE_COLS + col]++;
  }

  const coarseCounts = new Array<number>(COARSE_COLS * COARSE_ROWS).fill(0);
  for (let row = 0; row < FINE_ROWS; row++) {
    const coarseRow = Math.floor(row / BLOCK_ROWS);
    for (let col = 0; col < FINE_COLS; col++) {
      const coarseCol = Math.floor(col / BLOCK_COLS);
      coarseCounts[coarseRow * COARSE_COLS + coarseCol] += fineCounts[row * FINE_COLS + col];
    }
  }

  return {
    fine: { cols: FINE_COLS, rows: FINE_ROWS, counts: fineCounts, levels: quantiseLevels(fineCounts) },
    coarse: {
      cols: COARSE_COLS,
      rows: COARSE_ROWS,
      counts: coarseCounts,
      levels: quantiseLevels(coarseCounts),
    },
  };
}
